// Code generated by mockery v1.0.0, and other versions, with manual fixups.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"go.temporal.io/sdk/client"

	"go.temporal.io/api/enums/v1"
	"go.temporal.io/sdk/converter"

	"github.com/stretchr/testify/mock"

	"go.temporal.io/api/operatorservice/v1"

	"go.temporal.io/api/workflowservice/v1"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CancelWorkflow provides a mock function with given fields: ctx, workflowID, runID
func (_m *Client) CancelWorkflow(ctx context.Context, workflowID string, runID string) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckHealth provides a mock function with given fields: ctx, request
func (_m *Client) CheckHealth(ctx context.Context, request *client.CheckHealthRequest) (*client.CheckHealthResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Close provides a mock function with given fields:
func (_m *Client) Close() {
	_ = "STUB: not implemented"

	// CompleteActivity provides a mock function with given fields: ctx, taskToken, result, err
	return
}

func (_m *Client) CompleteActivity(ctx context.Context, taskToken []byte, result interface{}, err error) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityWithOptions provides a mock function with given fields: ctx, opts
func (_m *Client) CompleteActivityWithOptions(ctx context.Context, opts client.CompleteActivityOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByID provides a mock function with given fields: ctx, namespace, workflowID, runID, activityID, result, err
func (_m *Client) CompleteActivityByID(ctx context.Context, namespace string, workflowID string, runID string, activityID string, result interface{}, err error) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByIDWithOptions provides a mock function with given fields: ctx, opts
func (_m *Client) CompleteActivityByIDWithOptions(ctx context.Context, opts client.CompleteActivityByIDOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByActivityID provides a mock function with given fields: ctx, namespace, activityID, activityRunID, result, err
func (_m *Client) CompleteActivityByActivityID(ctx context.Context, namespace string, activityID string, activityRunID string, result interface{}, err error) error {
	_ = "STUB: not implemented"
	return nil
}

// CompleteActivityByActivityIDWithOptions provides a mock function with given fields: ctx, opts
func (_m *Client) CompleteActivityByActivityIDWithOptions(ctx context.Context, opts client.CompleteActivityByActivityIDOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// CountWorkflow provides a mock function with given fields: ctx, request
func (_m *Client) CountWorkflow(ctx context.Context, request *workflowservice.CountWorkflowExecutionsRequest) (*workflowservice.CountWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeploymentClient provides a mock function with given fields:
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *Client) DeploymentClient() client.DeploymentClient {
	_ = "STUB: not implemented"
	return *new(client.DeploymentClient)
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// DescribeTaskQueue provides a mock function with given fields: ctx, taskqueue, taskqueueType
func (_m *Client) DescribeTaskQueue(ctx context.Context, taskqueue string, taskqueueType enums.TaskQueueType) (*workflowservice.DescribeTaskQueueResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeTaskQueueEnhanced provides a mock function with given fields: ctx, options
func (_m *Client) DescribeTaskQueueEnhanced(ctx context.Context, options client.DescribeTaskQueueEnhancedOptions) (client.TaskQueueDescription, error) {
	_ = "STUB: not implemented"
	return *new(client.TaskQueueDescription), nil
}

// DescribeWorkflowExecution provides a mock function with given fields: ctx, workflowID, runID
func (_m *Client) DescribeWorkflowExecution(ctx context.Context, workflowID string, runID string) (*workflowservice.DescribeWorkflowExecutionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ExecuteWorkflow provides a mock function with given fields: ctx, options, workflow, args
func (_m *Client) ExecuteWorkflow(ctx context.Context, options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) (client.WorkflowRun, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun), nil
}

// GetSearchAttributes provides a mock function with given fields: ctx
func (_m *Client) GetSearchAttributes(ctx context.Context) (*workflowservice.GetSearchAttributesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetWorkerBuildIdCompatibility provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore for SDK
func (_m *Client) GetWorkerBuildIdCompatibility(ctx context.Context, options *client.GetWorkerBuildIdCompatibilityOptions) (*client.WorkerBuildIDVersionSets, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK

// GetWorkerTaskReachability provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore for SDK mocks
func (_m *Client) GetWorkerTaskReachability(ctx context.Context, options *client.GetWorkerTaskReachabilityOptions) (*client.WorkerTaskReachability, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

// GetWorkerVersioningRules provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore for SDK mocks
func (_m *Client) GetWorkerVersioningRules(ctx context.Context, options client.GetWorkerVersioningOptions) (*client.WorkerVersioningRules, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

// GetWorkflow provides a mock function with given fields: ctx, workflowID, runID
func (_m *Client) GetWorkflow(ctx context.Context, workflowID string, runID string) client.WorkflowRun {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun)
}

// GetWorkflowHistory provides a mock function with given fields: ctx, workflowID, runID, isLongPoll, filterType
func (_m *Client) GetWorkflowHistory(ctx context.Context, workflowID string, runID string, isLongPoll bool, filterType enums.HistoryEventFilterType) client.HistoryEventIterator {
	_ = "STUB: not implemented"
	return *new(client.HistoryEventIterator)
}

// GetWorkflowUpdateHandle provides a mock function with given fields: ref
func (_m *Client) GetWorkflowUpdateHandle(ref client.GetWorkflowUpdateHandleOptions) client.WorkflowUpdateHandle {
	_ = "STUB: not implemented"
	return *new(client.WorkflowUpdateHandle)
}

// ListArchivedWorkflow provides a mock function with given fields: ctx, request
func (_m *Client) ListArchivedWorkflow(ctx context.Context, request *workflowservice.ListArchivedWorkflowExecutionsRequest) (*workflowservice.ListArchivedWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListClosedWorkflow provides a mock function with given fields: ctx, request
func (_m *Client) ListClosedWorkflow(ctx context.Context, request *workflowservice.ListClosedWorkflowExecutionsRequest) (*workflowservice.ListClosedWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListOpenWorkflow provides a mock function with given fields: ctx, request
func (_m *Client) ListOpenWorkflow(ctx context.Context, request *workflowservice.ListOpenWorkflowExecutionsRequest) (*workflowservice.ListOpenWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListWorkflow provides a mock function with given fields: ctx, request
func (_m *Client) ListWorkflow(ctx context.Context, request *workflowservice.ListWorkflowExecutionsRequest) (*workflowservice.ListWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewWithStartWorkflowOperation provides a mock function with given fields: options, workflow, args
func (_m *Client) NewWithStartWorkflowOperation(options client.StartWorkflowOptions, workflow interface{}, args ...interface{}) client.WithStartWorkflowOperation {
	_ = "STUB: not implemented"
	return *new(client.WithStartWorkflowOperation)
}

// OperatorService provides a mock function with given fields:
func (_m *Client) OperatorService() operatorservice.OperatorServiceClient {
	_ = "STUB: not implemented"
	return *new(operatorservice.OperatorServiceClient)
}

// QueryWorkflow provides a mock function with given fields: ctx, workflowID, runID, queryType, args
func (_m *Client) QueryWorkflow(ctx context.Context, workflowID string, runID string, queryType string, args ...interface{}) (converter.EncodedValue, error) {
	_ = "STUB: not implemented"
	return *new(converter.EncodedValue), nil
}

// QueryWorkflowWithOptions provides a mock function with given fields: ctx, request
func (_m *Client) QueryWorkflowWithOptions(ctx context.Context, request *client.QueryWorkflowWithOptionsRequest) (*client.QueryWorkflowWithOptionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RecordActivityHeartbeat provides a mock function with given fields: ctx, taskToken, details
func (_m *Client) RecordActivityHeartbeat(ctx context.Context, taskToken []byte, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeatWithOptions provides a mock function with given fields: ctx, opts
func (_m *Client) RecordActivityHeartbeatWithOptions(ctx context.Context, opts client.RecordActivityHeartbeatOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeatByID provides a mock function with given fields: ctx, namespace, workflowID, runID, activityID, details
func (_m *Client) RecordActivityHeartbeatByID(ctx context.Context, namespace string, workflowID string, runID string, activityID string, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecordActivityHeartbeatByIDWithOptions provides a mock function with given fields: ctx, opts
func (_m *Client) RecordActivityHeartbeatByIDWithOptions(ctx context.Context, opts client.RecordActivityHeartbeatByIDOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ResetWorkflowExecution provides a mock function with given fields: ctx, request
func (_m *Client) ResetWorkflowExecution(ctx context.Context, request *workflowservice.ResetWorkflowExecutionRequest) (*workflowservice.ResetWorkflowExecutionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ScanWorkflow provides a mock function with given fields: ctx, request
//
//lint:ignore SA1019 the server API was deprecated.
func (_m *Client) ScanWorkflow(ctx context.Context, request *workflowservice.ScanWorkflowExecutionsRequest) (*workflowservice.ScanWorkflowExecutionsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 the server API was deprecated.

//lint:ignore SA1019 the server API was deprecated.

//lint:ignore SA1019 the server API was deprecated.

//lint:ignore SA1019 the server API was deprecated.

//lint:ignore SA1019 the server API was deprecated.

// ScheduleClient provides a mock function with given fields:
func (_m *Client) ScheduleClient() client.ScheduleClient {
	_ = "STUB: not implemented"
	return *new(client.ScheduleClient)
}

// SignalWithStartWorkflow provides a mock function with given fields: ctx, workflowID, signalName, signalArg, options, workflow, workflowArgs
func (_m *Client) SignalWithStartWorkflow(ctx context.Context, workflowID string, signalName string, signalArg interface{}, options client.StartWorkflowOptions, workflow interface{}, workflowArgs ...interface{}) (client.WorkflowRun, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowRun), nil
}

// SignalWorkflow provides a mock function with given fields: ctx, workflowID, runID, signalName, arg
func (_m *Client) SignalWorkflow(ctx context.Context, workflowID string, runID string, signalName string, arg interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// TerminateWorkflow provides a mock function with given fields: ctx, workflowID, runID, reason, details
func (_m *Client) TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWithStartWorkflow provides a mock function with given fields: ctx, options
func (_m *Client) UpdateWithStartWorkflow(ctx context.Context, options client.UpdateWithStartWorkflowOptions) (client.WorkflowUpdateHandle, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowUpdateHandle), nil
}

// UpdateWorkerBuildIdCompatibility provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore for SDK mocks
func (_m *Client) UpdateWorkerBuildIdCompatibility(ctx context.Context, options *client.UpdateWorkerBuildIdCompatibilityOptions) error {
	_ = "STUB: not implemented"
	return nil
}

//lint:ignore SA1019 ignore for SDK mocks

// UpdateWorkerVersioningRules provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore for SDK mocks
func (_m *Client) UpdateWorkerVersioningRules(ctx context.Context, options client.UpdateWorkerVersioningRulesOptions) (*client.WorkerVersioningRules, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

//lint:ignore SA1019 ignore for SDK mocks

// UpdateWorkflow provides a mock function with given fields: ctx, options
func (_m *Client) UpdateWorkflow(ctx context.Context, options client.UpdateWorkflowOptions) (client.WorkflowUpdateHandle, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowUpdateHandle), nil
}

// UpdateWorkflowExecutionOptions provides a mock function with given fields: ctx, options
func (_m *Client) UpdateWorkflowExecutionOptions(ctx context.Context, options client.UpdateWorkflowExecutionOptionsRequest) (client.WorkflowExecutionOptions, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkflowExecutionOptions), nil
}

// DescribeWorkflow implements client.Client.
func (_m *Client) DescribeWorkflow(ctx context.Context, workflowID string, runID string) (*client.WorkflowExecutionDescription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (_m *Client) ExecuteActivity(ctx context.Context, options client.StartActivityOptions, activity any, args ...any) (client.ActivityHandle, error) {
	_ = "STUB: not implemented"
	return *new(client.ActivityHandle), nil
}

func (_m *Client) GetActivityHandle(options client.GetActivityHandleOptions) client.ActivityHandle {
	_ = "STUB: not implemented"
	return *new(client.ActivityHandle)
}

func (_m *Client) ListActivities(ctx context.Context, options client.ListActivitiesOptions) (client.ListActivitiesResult, error) {
	_ = "STUB: not implemented"
	return *new(client.ListActivitiesResult), nil
}

func (_m *Client) CountActivities(ctx context.Context, options client.CountActivitiesOptions) (*client.CountActivitiesResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewNexusClient provides a mock function with given fields: options
func (_m *Client) NewNexusClient(options client.NexusClientOptions) (client.NexusClient, error) {
	_ = "STUB: not implemented"
	return *new(client.NexusClient), nil
}

// GetNexusOperationHandle provides a mock function with given fields: options
func (_m *Client) GetNexusOperationHandle(options client.GetNexusOperationHandleOptions) client.NexusOperationHandle {
	_ = "STUB: not implemented"
	return *new(client.NexusOperationHandle)
}

// ListNexusOperations provides a mock function with given fields: ctx, options
func (_m *Client) ListNexusOperations(ctx context.Context, options client.ListNexusOperationsOptions) (client.ListNexusOperationsResult, error) {
	_ = "STUB: not implemented"
	return *new(client.ListNexusOperationsResult), nil
}

// CountNexusOperations provides a mock function with given fields: ctx, options
func (_m *Client) CountNexusOperations(ctx context.Context, options client.CountNexusOperationsOptions) (*client.CountNexusOperationsResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WorkerDeploymentClient provides a mock function with given fields:
func (_m *Client) WorkerDeploymentClient() client.WorkerDeploymentClient {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentClient)
}

// WorkflowService provides a mock function with given fields:
func (_m *Client) WorkflowService() workflowservice.WorkflowServiceClient {
	_ = "STUB: not implemented"
	return *new(workflowservice.WorkflowServiceClient)
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	_ = "STUB: not implemented"
	return nil
}
