// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// DeploymentListIterator is an autogenerated mock type for the DeploymentListIterator type
type DeploymentListIterator struct {
	mock.Mock
}

// HasNext provides a mock function with given fields:
func (_m *DeploymentListIterator) HasNext() bool { _ = "STUB: not implemented"; return false }

// Next provides a mock function with given fields:
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentListIterator) Next() (*client.DeploymentListEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// NewDeploymentListIterator creates a new instance of DeploymentListIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeploymentListIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeploymentListIterator {
	_ = "STUB: not implemented"
	return nil
}
