// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// DeploymentClient is an autogenerated mock type for the DeploymentClient type
type DeploymentClient struct {
	mock.Mock
}

// Describe provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentClient) Describe(ctx context.Context, options client.DeploymentDescribeOptions) (client.DeploymentDescription, error) {
	_ = "STUB: not implemented"
	return *new(client.DeploymentDescription), nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// GetCurrent provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentClient) GetCurrent(ctx context.Context, options client.DeploymentGetCurrentOptions) (client.DeploymentGetCurrentResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.DeploymentGetCurrentResponse), nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// GetReachability provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentClient) GetReachability(ctx context.Context, options client.DeploymentGetReachabilityOptions) (client.DeploymentReachabilityInfo, error) {
	_ = "STUB: not implemented"
	return *new(client.DeploymentReachabilityInfo), nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// List provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentClient) List(ctx context.Context, options client.DeploymentListOptions) (client.DeploymentListIterator, error) {
	_ = "STUB: not implemented"
	return *new(client.DeploymentListIterator), nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// SetCurrent provides a mock function with given fields: ctx, options
//
//lint:ignore SA1019 ignore deprecated versioning APIs
func (_m *DeploymentClient) SetCurrent(ctx context.Context, options client.DeploymentSetCurrentOptions) (client.DeploymentSetCurrentResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.DeploymentSetCurrentResponse), nil
}

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

//lint:ignore SA1019 ignore deprecated versioning APIs

// NewDeploymentClient creates a new instance of DeploymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeploymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeploymentClient {
	_ = "STUB: not implemented"
	return nil
}
