// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"github.com/stretchr/testify/mock"
	historypb "go.temporal.io/api/history/v1"
)

// HistoryEventIterator is an autogenerated mock type for the HistoryEventIterator type
type HistoryEventIterator struct {
	mock.Mock
}

// HasNext provides a mock function with given fields:
func (_m *HistoryEventIterator) HasNext() bool { _ = "STUB: not implemented"; return false }

// Next provides a mock function with given fields:
func (_m *HistoryEventIterator) Next() (*historypb.HistoryEvent, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewHistoryEventIterator creates a new instance of HistoryEventIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryEventIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryEventIterator {
	_ = "STUB: not implemented"
	return nil
}
