// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
	"go.temporal.io/api/workflowservice/v1"
)

// NamespaceClient is an autogenerated mock type for the NamespaceClient type
type NamespaceClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *NamespaceClient) Close() {
	_ = "STUB: not implemented"

	// Describe provides a mock function with given fields: ctx, name
	return
}

func (_m *NamespaceClient) Describe(ctx context.Context, name string) (*workflowservice.DescribeNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Register provides a mock function with given fields: ctx, request
func (_m *NamespaceClient) Register(ctx context.Context, request *workflowservice.RegisterNamespaceRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Update provides a mock function with given fields: ctx, request
func (_m *NamespaceClient) Update(ctx context.Context, request *workflowservice.UpdateNamespaceRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// NewNamespaceClient creates a new instance of NamespaceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNamespaceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NamespaceClient {
	_ = "STUB: not implemented"
	return nil
}
