// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"github.com/stretchr/testify/mock"
	"go.temporal.io/sdk/client"
)

// ScheduleListIterator is an autogenerated mock type for the ScheduleListIterator type
type ScheduleListIterator struct {
	mock.Mock
}

// HasNext provides a mock function with given fields:
func (_m *ScheduleListIterator) HasNext() bool { _ = "STUB: not implemented"; return false }

// Next provides a mock function with given fields:
func (_m *ScheduleListIterator) Next() (*client.ScheduleListEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewScheduleListIterator creates a new instance of ScheduleListIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleListIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleListIterator {
	_ = "STUB: not implemented"
	return nil
}
