// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// ScheduleHandle is an autogenerated mock type for the ScheduleHandle type
type ScheduleHandle struct {
	mock.Mock
}

// Backfill provides a mock function with given fields: ctx, options
func (_m *ScheduleHandle) Backfill(ctx context.Context, options client.ScheduleBackfillOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete provides a mock function with given fields: ctx
func (_m *ScheduleHandle) Delete(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Describe provides a mock function with given fields: ctx
func (_m *ScheduleHandle) Describe(ctx context.Context) (*client.ScheduleDescription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetID provides a mock function with given fields:
func (_m *ScheduleHandle) GetID() string { _ = "STUB: not implemented"; return "" }

// Pause provides a mock function with given fields: ctx, options
func (_m *ScheduleHandle) Pause(ctx context.Context, options client.SchedulePauseOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Trigger provides a mock function with given fields: ctx, options
func (_m *ScheduleHandle) Trigger(ctx context.Context, options client.ScheduleTriggerOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Unpause provides a mock function with given fields: ctx, options
func (_m *ScheduleHandle) Unpause(ctx context.Context, options client.ScheduleUnpauseOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Update provides a mock function with given fields: ctx, options
func (_m *ScheduleHandle) Update(ctx context.Context, options client.ScheduleUpdateOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// NewScheduleHandle creates a new instance of ScheduleHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleHandle {
	_ = "STUB: not implemented"
	return nil
}
