// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// ScheduleClient is an autogenerated mock type for the ScheduleClient type
type ScheduleClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) Create(ctx context.Context, options client.ScheduleOptions) (client.ScheduleHandle, error) {
	_ = "STUB: not implemented"
	return *new(client.ScheduleHandle), nil
}

// GetHandle provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleClient) GetHandle(ctx context.Context, scheduleID string) client.ScheduleHandle {
	_ = "STUB: not implemented"
	return *new(client.ScheduleHandle)
}

// List provides a mock function with given fields: ctx, options
func (_m *ScheduleClient) List(ctx context.Context, options client.ScheduleListOptions) (client.ScheduleListIterator, error) {
	_ = "STUB: not implemented"
	return *new(client.ScheduleListIterator), nil
}

// NewScheduleClient creates a new instance of ScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleClient {
	_ = "STUB: not implemented"
	return nil
}
