// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import "github.com/stretchr/testify/mock"

// Value is an autogenerated mock type for the Value type
type Value struct {
	mock.Mock
}

// Get provides a mock function with given fields: valuePtr
func (_m *Value) Get(valuePtr interface{}) error { _ = "STUB: not implemented"; return nil }

// HasValue provides a mock function with given fields:
func (_m *Value) HasValue() bool { _ = "STUB: not implemented"; return false }

// NewEncodedValue creates a new instance of Value. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncodedValue(t interface {
	mock.TestingT
	Cleanup(func())
}) *Value {
	_ = "STUB: not implemented"
	return nil
}
