// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// WorkflowUpdateHandle is an autogenerated mock type for the WorkflowUpdateHandle type
type WorkflowUpdateHandle struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, valuePtr
func (_m *WorkflowUpdateHandle) Get(ctx context.Context, valuePtr interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RunID provides a mock function with given fields:
func (_m *WorkflowUpdateHandle) RunID() string { _ = "STUB: not implemented"; return "" }

// UpdateID provides a mock function with given fields:
func (_m *WorkflowUpdateHandle) UpdateID() string { _ = "STUB: not implemented"; return "" }

// WorkflowID provides a mock function with given fields:
func (_m *WorkflowUpdateHandle) WorkflowID() string { _ = "STUB: not implemented"; return "" }

// NewWorkflowUpdateHandle creates a new instance of WorkflowUpdateHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowUpdateHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowUpdateHandle {
	_ = "STUB: not implemented"
	return nil
}
