// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// WorkerDeploymentHandle is an autogenerated mock type for the WorkerDeploymentHandle type
type WorkerDeploymentHandle struct {
	mock.Mock
}

// DeleteVersion provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) DeleteVersion(ctx context.Context, options client.WorkerDeploymentDeleteVersionOptions) (client.WorkerDeploymentDeleteVersionResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentDeleteVersionResponse), nil
}

// Describe provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) Describe(ctx context.Context, options client.WorkerDeploymentDescribeOptions) (client.WorkerDeploymentDescribeResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentDescribeResponse), nil
}

// DescribeVersion provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) DescribeVersion(ctx context.Context, options client.WorkerDeploymentDescribeVersionOptions) (client.WorkerDeploymentVersionDescription, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentVersionDescription), nil
}

// SetCurrentVersion provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) SetCurrentVersion(ctx context.Context, options client.WorkerDeploymentSetCurrentVersionOptions) (client.WorkerDeploymentSetCurrentVersionResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentSetCurrentVersionResponse), nil
}

// SetRampingVersion provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) SetRampingVersion(ctx context.Context, options client.WorkerDeploymentSetRampingVersionOptions) (client.WorkerDeploymentSetRampingVersionResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentSetRampingVersionResponse), nil
}

// UpdateVersionMetadata provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentHandle) UpdateVersionMetadata(ctx context.Context, options client.WorkerDeploymentUpdateVersionMetadataOptions) (client.WorkerDeploymentUpdateVersionMetadataResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentUpdateVersionMetadataResponse), nil
}

// NewWorkerDeploymentHandle creates a new instance of WorkerDeploymentHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerDeploymentHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerDeploymentHandle {
	_ = "STUB: not implemented"
	return nil
}
