// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// WorkerDeploymentListIterator is an autogenerated mock type for the WorkerDeploymentListIterator type
type WorkerDeploymentListIterator struct {
	mock.Mock
}

// HasNext provides a mock function with given fields:
func (_m *WorkerDeploymentListIterator) HasNext() bool { _ = "STUB: not implemented"; return false }

// Next provides a mock function with given fields:
func (_m *WorkerDeploymentListIterator) Next() (*client.WorkerDeploymentListEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewWorkerDeploymentListIterator creates a new instance of WorkerDeploymentListIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerDeploymentListIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerDeploymentListIterator {
	_ = "STUB: not implemented"
	return nil
}
