// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// WorkerDeploymentClient is an autogenerated mock type for the WorkerDeploymentClient type
type WorkerDeploymentClient struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentClient) Delete(ctx context.Context, options client.WorkerDeploymentDeleteOptions) (client.WorkerDeploymentDeleteResponse, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentDeleteResponse), nil
}

// GetHandle provides a mock function with given fields: name
func (_m *WorkerDeploymentClient) GetHandle(name string) client.WorkerDeploymentHandle {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentHandle)
}

// List provides a mock function with given fields: ctx, options
func (_m *WorkerDeploymentClient) List(ctx context.Context, options client.WorkerDeploymentListOptions) (client.WorkerDeploymentListIterator, error) {
	_ = "STUB: not implemented"
	return *new(client.WorkerDeploymentListIterator), nil
}

// NewWorkerDeploymentClient creates a new instance of WorkerDeploymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerDeploymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerDeploymentClient {
	_ = "STUB: not implemented"
	return nil
}
