// Code generated by mockery v1.0.0.
// Modified manually for type alias to work correctly.
// https://github.com/vektra/mockery/issues/236

package mocks

import (
	"context"

	"go.temporal.io/sdk/client"

	"github.com/stretchr/testify/mock"
)

// WorkflowRun is an autogenerated mock type for the WorkflowRun type
type WorkflowRun struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, valuePtr
func (_m *WorkflowRun) Get(ctx context.Context, valuePtr interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// GetID provides a mock function with given fields:
func (_m *WorkflowRun) GetID() string { _ = "STUB: not implemented"; return "" }

// GetRunID provides a mock function with given fields:
func (_m *WorkflowRun) GetRunID() string { _ = "STUB: not implemented"; return "" }

// GetWithOptions provides a mock function with given fields: ctx, valuePtr, options
func (_m *WorkflowRun) GetWithOptions(ctx context.Context, valuePtr interface{}, options client.WorkflowRunGetOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// NewWorkflowRun creates a new instance of WorkflowRun. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowRun(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowRun {
	_ = "STUB: not implemented"
	return nil
}
